spring:
  application:
    name: BigBite-Backend

  datasource:
    url: jdbc:mysql://localhost:3306/bigbite?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true