spring:
  application:
    name: BigBite-Backend

  datasource:
    url: jdbc:mysql://localhost:3306/bigbite?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:gcp-credentials-bigbite.json